version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      default:
        ipv4_address: 172.28.1.1
    volumes:
      - mydb:/var/lib/mysql

volumes:
    mydb:

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
